In [16]:
import numpy as np

In [17]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [18]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]


In [19]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[1,1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)

<class 'numpy.int64'>
2
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [20]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 7, 20, 15, 30)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 7, 20, 15, 30)
7560000
[0.97977252 0.67962896 0.69575442 0.93985434 0.64320337 0.48323859
 0.53996422 0.2352041  0.31659305 0.219718   0.64504718 0.46606192
 0.21577047 0.36842507 0.97011744 0.87576738 0.01031367 0.30946771
 0.49056507 0.14563915 0.12566553 0.86659693 0.61545893 0.2697756
 0.24547237 0.09622568 0.04268751 0.66328619 0.75289728 0.42305947] 

[0.97977252 0.80984724 0.62231134 0.62993847 0.07561112 0.77173085
 0.97831807 0.62514275 0.20579355 0.36195531 0.33924833 0.55856893
 0.68694841 0.88486795 0.23914952] 

[0.7425879  0.65411112 0.23382748 0.08762043 0.25089226 0.82355491
 0.00516189 0.5231699  0.22619336 0.48187967 0.38749881 0.92330102]


In [21]:
# Want to see complete array ?
print (arr_mD)

[[[[[[9.79772518e-01 6.79628962e-01 6.95754425e-01 ... 6.63286191e-01
      7.52897277e-01 4.23059472e-01]
     [8.09847237e-01 2.67889189e-02 4.91506069e-01 ... 2.53540666e-01
      2.49262484e-01 3.26857427e-01]
     [6.22311343e-01 8.07295645e-01 5.85189815e-01 ... 1.00969948e-01
      2.29863076e-01 7.97460776e-01]
     ...
     [6.86948406e-01 5.74434701e-02 4.68714212e-01 ... 3.09937195e-01
      6.61403744e-01 5.29965666e-01]
     [8.84867955e-01 1.84135595e-01 7.59298135e-01 ... 4.43259497e-01
      9.67699025e-01 4.00131428e-02]
     [2.39149519e-01 4.25603823e-02 7.22371011e-01 ... 7.93579793e-01
      3.78799216e-01 5.57673092e-01]]

    [[3.55061055e-01 8.81441809e-01 9.04281196e-01 ... 2.46895179e-01
      3.59170820e-01 1.96762134e-01]
     [9.84450730e-02 6.00167479e-01 3.36834808e-01 ... 1.32296494e-01
      7.95657777e-01 2.40695237e-01]
     [7.92257267e-01 7.95139106e-01 5.62051585e-01 ... 9.57508216e-01
      7.31745176e-01 6.12970445e-02]
     ...
     [1.24746210e

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [22]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [23]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3)

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]]


Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [24]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [27]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [29]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

Sum of Array Elements : 
 26
Mean of Array Elements : 
 6.5
Min of Array Elements : 
 5
Max of Array Elements : 
 8


In [30]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))

Square Root : 
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Sine value : 
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
