In [2]:
import numpy as np

In [3]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [4]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]


In [5]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[1,1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)

<class 'numpy.int64'>
2
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [6]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 7, 20, 15, 30)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 7, 20, 15, 30)
7560000
[0.50877001 0.52866949 0.59380038 0.58755346 0.08063629 0.07906126
 0.31437693 0.8034583  0.61184573 0.55135942 0.44081837 0.54437599
 0.16164597 0.91130948 0.07899539 0.0477353  0.14498892 0.69439917
 0.82892282 0.2071245  0.70665342 0.42917516 0.08697919 0.56873651
 0.26877989 0.79814945 0.97330278 0.48127499 0.37744972 0.25109234] 

[0.50877001 0.06073867 0.41928188 0.82632476 0.64959382 0.4281802
 0.3583082  0.81877565 0.58959908 0.08092582 0.16830335 0.92380368
 0.27706858 0.64566788 0.16598747] 

[0.61732682 0.2606438  0.28857483 0.9324961  0.89473315 0.54633697
 0.98756995 0.67204538 0.06825513 0.14247047 0.57601676 0.31761117]


In [7]:
# Want to see complete array ?
print (arr_mD)

[[[[[[5.08770005e-01 5.28669485e-01 5.93800376e-01 ... 4.81274993e-01
      3.77449716e-01 2.51092344e-01]
     [6.07386707e-02 6.58183972e-01 5.14892641e-01 ... 5.97124477e-01
      6.02474971e-01 8.45564942e-01]
     [4.19281876e-01 7.81987283e-01 6.32351988e-01 ... 8.65470240e-01
      3.10393076e-02 4.14846961e-01]
     ...
     [2.77068583e-01 3.84830268e-01 3.14242359e-01 ... 3.11146211e-01
      7.93442014e-01 6.42946957e-02]
     [6.45667877e-01 4.70498566e-03 2.88657833e-01 ... 5.00717027e-02
      3.68803355e-01 5.62819441e-01]
     [1.65987468e-01 6.49598535e-02 3.46913749e-01 ... 6.05076670e-01
      8.94181203e-01 4.69340730e-01]]

    [[2.29621414e-01 3.97446226e-01 9.76209747e-02 ... 4.19752100e-01
      9.47937017e-01 9.37811669e-01]
     [8.60398751e-01 8.61946213e-01 5.87058514e-01 ... 8.43805711e-01
      5.16220262e-01 2.13874766e-01]
     [1.44328074e-02 5.71066343e-01 4.87461356e-01 ... 8.89365442e-01
      5.63334534e-01 8.99865216e-01]
     ...
     [8.27106972e

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [8]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [9]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3)

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]]


Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [10]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [13]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [15]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

Sum of Array Elements : 
 26
Mean of Array Elements : 
 6.5
Min of Array Elements : 
 5
Max of Array Elements : 
 8


In [16]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))

Square Root : 
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Sine value : 
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
