In [2]:
import numpy as np

In [3]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [4]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]


In [5]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[1,1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)

<class 'numpy.int64'>
2
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [6]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 7, 20, 15, 30)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 7, 20, 15, 30)
7560000
[0.4020354  0.99293244 0.96453374 0.75760061 0.56955312 0.07465974
 0.93891284 0.62512618 0.99900866 0.82820718 0.02157865 0.74205521
 0.30751694 0.78993698 0.22832093 0.17198027 0.87514902 0.70512126
 0.61510928 0.56767601 0.25267393 0.05693545 0.35756012 0.74062699
 0.77678716 0.13539335 0.16890374 0.2404056  0.46583125 0.00268624] 

[0.4020354  0.80211667 0.04783796 0.84237517 0.56514742 0.53183545
 0.71949566 0.12278345 0.28544064 0.30011036 0.4146292  0.50747588
 0.97072098 0.25297615 0.29298563] 

[0.75667386 0.09017678 0.88386938 0.34634251 0.20876106 0.7119993
 0.5047152  0.7889386  0.85045785 0.1005795  0.48658011 0.78978305]


In [7]:
# Want to see complete array ?
print (arr_mD)

[[[[[[4.02035397e-01 9.92932441e-01 9.64533742e-01 ... 2.40405601e-01
      4.65831255e-01 2.68624298e-03]
     [8.02116673e-01 2.86299834e-01 9.70592642e-01 ... 2.23365886e-01
      6.12351980e-01 4.29657017e-01]
     [4.78379618e-02 1.25533279e-02 5.45872191e-01 ... 6.03059369e-01
      6.90744963e-01 8.34360095e-01]
     ...
     [9.70720981e-01 5.85770508e-01 4.72876957e-01 ... 1.09634911e-01
      9.88630504e-01 8.68320278e-01]
     [2.52976148e-01 1.53131631e-01 6.30242178e-02 ... 2.50542028e-01
      4.77355852e-01 2.50782807e-01]
     [2.92985634e-01 8.24661865e-01 3.60882549e-01 ... 2.42997312e-01
      9.27491468e-01 4.26632251e-01]]

    [[2.07399831e-01 6.83496873e-01 7.21958254e-01 ... 7.77144936e-01
      4.50038319e-01 3.14540307e-01]
     [7.51406158e-01 5.06663037e-01 4.59417137e-01 ... 5.62827657e-01
      1.76032279e-01 9.59481991e-01]
     [5.37620787e-01 3.52651876e-01 7.36342988e-01 ... 5.92240383e-02
      1.81641919e-01 4.32178164e-01]
     ...
     [1.28492706e

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [8]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [9]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3)

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]]


Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [10]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [13]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [15]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

Sum of Array Elements : 
 26
Mean of Array Elements : 
 6.5
Min of Array Elements : 
 5
Max of Array Elements : 
 8


In [16]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))

Square Root : 
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Sine value : 
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
