In [1]:
import numpy as np

In [2]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [3]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]


In [4]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[1,1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)

<class 'numpy.int64'>
2
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [5]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 7, 20, 15, 30)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 7, 20, 15, 30)
7560000
[0.19391663 0.0028818  0.98804018 0.25985925 0.84019167 0.99339676
 0.51127025 0.09282669 0.63487841 0.00821065 0.02728708 0.32888383
 0.73563231 0.77997098 0.24685576 0.8862191  0.59881045 0.53452646
 0.97058336 0.34428137 0.57316145 0.4757028  0.65682472 0.18399385
 0.79650681 0.28140677 0.35308554 0.08267938 0.6253424  0.84338456] 

[0.19391663 0.8699111  0.92882012 0.64273805 0.87819249 0.44310499
 0.51992295 0.10389781 0.92054925 0.93448183 0.89290009 0.42707101
 0.5775572  0.48672038 0.97688957] 

[0.45733011 0.62967659 0.22949844 0.59288398 0.51322939 0.76538983
 0.06372894 0.88885872 0.85066632 0.71263359 0.42020955 0.87281102]


In [6]:
# Want to see complete array ?
print (arr_mD)

[[[[[[1.93916633e-01 2.88179626e-03 9.88040184e-01 ... 8.26793837e-02
      6.25342401e-01 8.43384559e-01]
     [8.69911098e-01 2.89779398e-01 6.42334199e-02 ... 1.79440463e-01
      4.72252901e-01 2.89590119e-01]
     [9.28820120e-01 1.74064681e-01 5.18458460e-01 ... 5.87496798e-01
      7.13143156e-01 8.22475088e-01]
     ...
     [5.77557199e-01 4.51553508e-01 1.67113824e-01 ... 7.81150209e-01
      9.39795291e-01 9.56279378e-01]
     [4.86720379e-01 6.06407232e-02 5.72787422e-01 ... 2.78712369e-01
      1.05954341e-01 5.64015252e-01]
     [9.76889565e-01 1.64509809e-01 5.23052486e-02 ... 7.34520729e-01
      8.12118605e-01 5.19118337e-01]]

    [[3.61592410e-01 1.95517556e-01 3.03574344e-01 ... 2.88996195e-01
      4.00725182e-01 7.63563244e-01]
     [2.93469505e-01 2.48061457e-01 3.23432500e-02 ... 6.75762992e-01
      7.82486517e-01 5.88719947e-01]
     [4.54907695e-01 2.68522621e-01 5.68721207e-01 ... 5.93810727e-01
      5.79581377e-01 5.63963900e-01]
     ...
     [9.03372797e

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [7]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [8]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3)

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]]


Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [9]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [12]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [14]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

Sum of Array Elements : 
 26
Mean of Array Elements : 
 6.5
Min of Array Elements : 
 5
Max of Array Elements : 
 8


In [15]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))

Square Root : 
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Sine value : 
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
